---
title: Nsmsn.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
name: Nick Simson
description: Communication Designer
avatar: http://nsmsn.github.io/images/monogram.png
footer-links:
  dribbble: nsmsn
  email: 
  facebook: 
  flickr: 
  github: nsmsn
  instagram: nsimson
  linkedin: 
  pinterest: 
  rss: 
  twitter: nsmsn
  stackoverflow: 
disqus: nsmsn
google_analytics: UA-45863222-1
url: http://nicksimson.com
baseurl: ''
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
version: v1.0.0
sass:
  sass_dir: _scss
  style: :compressed
gems:
- jemoji
- jekyll-sitemap
- jekyll-redirect-from
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
